### ISSUE TITLE
models.logger missing 

### ISSUE THREAD

**Issue by dougpat** [Tonio101/YoLinkAPI_V2#1]
Excellent work!  Very useful. 
To get the code to run I needed to add the logger.py file from your YoLinkHomeAssistant/src project into YoLinkAPI_V2/src/models

**Comment by Tonio101** [comment]
@dougpat lol, thanks! I forgot to include the `logger.py` file. Still WIP, but it seems stable enough, will have to refactor the code in YoLinkHomeAssistant to use the new API instead since thats the direction YoLink is heading.
