### ISSUE TITLE
requirements and configuration

### ISSUE THREAD

**Issue by tfcarlin** [Tonio101/YoLinkAPI_V2#2]
Thanks for sharing this!

I was missing the requirement: https://www.eclipse.org/paho/index.php?page=clients/python/index.php

queue was already installed.

This line appears to have an extra `.local`: `python3 src/yolinkv2.py --config src/yolink_data.local.json --debug`

**Comment by Tonio101** [comment]
Thanks @tfcarlin, glad its working on your end.
